version: '3.4'

services:
  yourprojectname:
    image: bloggingsystem
    build:
      context: .
      dockerfile: BloggingSystem/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "Password@123"
    ports:
      - "5432:5432"

